cbzapi = require('./lib/cebelcabiz-api.js')
console.log("# Cebelca.biz and InvoiceFox.com API JS Library")
console.log("Realy needs some more testing! This library can also be used with \"modern\" browsers using porter.js http://github.com/hij1nx/Porter\n\n")
console.log("    var cebelcaAPI = require('./lib/cebelcabiz-api.js')\n")
console.log("Run tests with:\n")
console.log("    npm test\n")
console.log("Make docs with:\n")
console.log("    npm start\n")
console.log("# JS API\n")
cbzapi("123456789abcdef").describe(function(doc) {
	console.log(doc)
})